version: '3'
services:
  nba_ml_standings_api:
    container_name: nba_ml_standings_api
    build: ./standings_for_ml
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env

  nba_api:
    container_name: nba_api
    build: ./nba_api_service
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env

  raw_nba_api:
    container_name: nba_raw_standings
    build: ./nba_raw_api_service
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env

  nba_scores_api:
    container_name: nba_scores
    build: ./nba_live_scores
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env

  flask_app:
    container_name: web_app
    build: ./nba_web_app
    ports:
      - "8080:80"
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env

  ml_model:
    container_name: nba_ml_model
    build: ./ml_model
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env

  datascience-notebook:
    image: jupyter/datascience-notebook
    volumes:
      - sql_live:/var/data
    env_file:
      - nba.env
    ports:
      - "8888:8888"
    container_name: jupyter_notebook
    command: "start-notebook.sh"

volumes:
  sql_live: